### ISSUE TITLE
Web API - Add New Thing

### ISSUE THREAD

**Issue by benfrancis** [moziot/gateway#27]
_As a developer of the MozIoT web app front end I want to add a new thing to the gateway_

We need an API call/calls which can be used to add a new thing to the gateway. This includes:
1. Adding a device to the gateway which has not yet been paired but the user wants to pair via a gateway adapter
2. Adding a device to the gateway database which has somehow already been paired via an adapter (e.g. ZigBee/Z-Wave controller) but not yet added to the database
3. Eventually also adding references to Web Things which are not hosted by the gateway itself but expose their Web Thing API directly

**Comment by benfrancis** [comment]
I think there a few steps to this:

1. Subscribe to a list of new things (i.e. things which adapters know about but which aren't yet in the gateway database)
2. Turn on pairing mode on adapters which support that
3. Add a Thing to the Thing database (possibly after the user assigning their own human readable name to it)
4. Clean up

My initial thoughts on implementation are:

**1. Subscribe to a list of new Things via WebSockets**:
```
GET ws://localhost:8080/new_things
Origin: localhost
Connection: Upgrade
Host: localhost
Upgrade: websocket
```

Question: Do we need to fall back to long polling for clients which don't support WebSockets?

**2. Turn on pairing mode**:
```
PUT /settings/pairing_mode
{
 "pairing_mode": true
}
```

**3. Add a new thing to the Thing database**, possibly with a user-created name:
```
POST /things/3532-5325-5325-53252
{
  "name": "My thing name",
  ....
}
```

**4. Close the WebSocket and turn off pairing mode** if not already timed out

**Comment by dhylands** [comment]
About polling. It has been my experience, that eventually you'll run across things that need polling. ZWave uses polling, but its done internally as part of Open-ZWave.

I think that having the adapter be responsible for polling sounds reasonable. Then it can pick an appropriate rate. We might want the ability to expose a polling rate for a device as some type of configurable parameters (so most likely a thing property).

**Comment by benfrancis** [comment]
> About polling. It has been my experience, that eventually you'll run across things that need polling. ZWave uses polling, but its done internally as part of Open-ZWave.

Yes, so openzwave may well use polling at a lower level. The Web API can then hopefully use WebSockets to push the results of that polling to the client as soon as they come through. My question on polling was just about falling back to HTTP long polling for browsers that don't support WebSockets, but probably not a priority for our prototype.

> I think that having the adapter be responsible for polling sounds reasonable. Then it can pick an appropriate rate. We might want the ability to expose a polling rate for a device as some type of configurable parameters (so most likely a thing property).

I don't think polling rate of an adapter is a property of a Web Thing, and neither WebSockets or HTTP long polling need to know about the polling rate an adapter may be using on the back end - they just keep a socket open and wait for changes to be pushed to the client.

Separately we are eventually going to want to be able to subscribe to Thing property changes over WebSockets too (see [here](https://moziot.github.io/wot/#subscriptions-with-websockets)), but I think that's a separate issue.

**Comment by benfrancis** [comment]
Alternative design:

**1. Open a WebSocket to subscribe to new Things**

```
GET ws://localhost:8080/new_things
Origin: localhost
Connection: Upgrade
Host: localhost
Upgrade: websocket
```
**2. Add a pair action to an actions queue**

Request:
```
POST http://localhost:8080/actions
{
  "name": "pair"
}
```
Response:
```
201 Created
{
  "name": "pair"
  "href": "/actions/123e4567-e89b-12d3-a456-426655"
}
```

This puts all adapters in pairing mode.

Thing descriptions of "new devices" can then be pushed to the client over the WebSocket. This might include things the adapter already knows about which aren't in the Thing database, and newly paired things as they are successfully paired.

```
{
  "name": "Smart Plug",
  ....
}
```

**3. Add a new thing to the Thing database**, possibly with a user-created name

```
POST /things/3532-5325-5325-53252
{
  "name": "My thing name",
  ....
}
```

If necessary pairing can be stopped before it automatically times out with an HTTP DELETE on the action item in the action queue

```
DELETE /actions/123e4567-e89b-12d3-a456-426655
```

**Comment by benfrancis** [comment]
I've made a start on the latter design (with an actions controller) in #29 

@dhylands: This makes me wonder about the usefulness of the current design of AdapterManager.addNewDevice() which adds a single device and resolves a promise with that device. I'm wondering if what we really need is just an AdapterManager.startPairing() method and then some separate way of pushing new Things through a WebSocket back to the client. That would include both things which the AdapterManager is aware of but which aren't yet in the Things database, and also newly paired things as they are paired.

**Comment by dhylands** [comment]
So I think that using a promise makes sense from the adapter API level.

We could easily rename addNewDevice to startPairing and have it return a promise (as before).

The controller layer would get the request and call the adapterManager and in the "then" of the promise would deliver the appropriate information via web socket.

**Comment by benfrancis** [comment]
Implemented by https://github.com/moziot/gateway/commit/05c8d6707c7f4fa24fbe7b414927d5f1b7bf9bae

Will file a follow up for adding a Web Thing by its URL
