### ISSUE TITLE
New device has empty name field

### ISSUE THREAD

**Issue by benfrancis** [moziot/gateway#36]
STR:
* Call AdapterManager.addNewDevice()
* print output resolved promise

Expected:
* name field populated

Actual:
* name field is an empty string

What's odd is that when you subsequently call AdapterManager.getDevices() the added device does have a name set.

**Comment by benfrancis** [comment]
@dhylands Can you think why this might be the case? Currently I'm working around it with a hack by setting a default string, but I would like to consistently show the adapter provided name as the default value in the text field when adding a device.

**Comment by dhylands** [comment]
I think that is the default (the empty string). We could probably do something to have the adapter fill in something if the name is empty (like perhaps use one of the manufacturer fields or something).

**Comment by dhylands** [comment]
FYI: Zigbee also has a name field for each device which defaults to the empty string.

**Comment by benfrancis** [comment]
What I don't understand is why the name is blank when the device is first added (when the Promise returns), but then has a name in the device list on adapter manager?

Defaulting to the product name (.e.g. Aeotec Smart Switch 6) would be great.

**Comment by dhylands** [comment]
I think I figured out the zwave issue. In ZWave, the promise is being resolved on the node-added notification. The default name comes from the first added user value.

So I think that the promise is being resolved too early, and I need to defer the notification until one of the later notifications.
