### ISSUE TITLE
Browsing to https://demo.box.knilxof.org:4443/ doesn't work properly n Chrome Desktop

### ISSUE THREAD

**Issue by dhylands** [moziot/gateway#57]
In Chrome on my linux desktop, if I browse to:
https://demo.box.knilxof.org:4443/
then I get the Blue background and "No devices yet."

If I browse to the same address using Chrome on my phone then it works.

Browsing to the same address using Firefox works fine (both desktop and phone).

Browsing to my local node server (https://192.168.0.24:4443/ - using a self-signed cert) works fine after doing the security exception (in Chrome/Firefox on desktop or phone)

**Comment by benfrancis** [comment]
The first time I tried I got an error:

GET https://demo.box.knilxof.org:4443/things/zb-0022a300001af3b7/properties/on net::ERR_BAD_SSL_CLIENT_AUTH_CERT

But it seems to be working now...

**Comment by dhylands** [comment]
It seems to be working fine for me now too.

I guess it would be good that if the REST API fails for some reason then we should report something rather than silently ignore it.

**Comment by dhylands** [comment]
I'm going to close this. I think it was caused by pagekite not having enough connections, and isn't related to Chrome at all.
